module "service" {
  source = "git@github.com:GitJMSeguradora/GitOps.git//terraform/aws/modules/ecs/services/"

  aws_region                   = "${var.aws_region}"
  gitops_bucket                = "${var.gitops_bucket}"
  tag_service                  = "${var.tag_service}"
  tag_environment              = "${var.tag_environment}"
  container_port               = "${var.container_port}"
  desired_containers           = "${var.desired_containers}"
  container_memory             = "${var.container_memory}"
  container_memory_reservation = "${var.container_memory_reservation}"
  ingress_cidr_blocks          = "${var.ingress_cidr_blocks}"
  ingress_ipv6_cidr_blocks     = "${var.ingress_ipv6_cidr_blocks}"
  health_check                 = "${var.health_check}"
  min_containers               = "${var.min_containers}"
  max_containers               = "${var.max_containers}"
  task_count_alarm             = "${var.task_count_alarm}"
  cloudwatch_notification      = "${var.cloudwatch_notification}"
  cpu_utilization_alarm        = "${var.cpu_utilization_alarm}"
  memory_utilization_alarm     = "${var.memory_utilization_alarm}"
  service_repository           = "${var.service_repository}"
  service_repository_tag       = "${var.service_repository_tag}"
  certificate_arn              = "${var.certificate_arn}"
}
